id: P000425
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ5668
  title: བདེ་མཆོག་ལཱུ་ཨི་པའི་ལུགས་ཀྱི་བསྐྱེད་རྫོགས་དམར་ཁྲིད
  author: ''
  volumes:
    dbf553b02eff4b56a776b63effbb9fca:
      image_group_id: I1KG1243
      title: Volume 1 of bde mchog lU i pa'i lugs kyi bskyed rdzogs dmar khrid
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
ebook_metadata:
  title: བདེ་མཆོག་ལཱུ་ཨི་པའི་ལུགས་ཀྱི་བསྐྱེད་རྫོགས་དམར་ཁྲིད
  author: ''
  sku: P000425
  cover: cover.jpg
  layers:
  - pagination
